### ISSUE TITLE
Can't craft the wooden axe head for the getting equipped quest.

### ISSUE THREAD

**Issue by levicc00123** [JadedPacks/Agrarian-Skies-2#9] opened 2019-06-23 23:31 UTC
![2019-06-23_17 25 25](https://user-images.githubusercontent.com/4361838/59983435-ac71e580-95dc-11e9-8f04-bc235dfc9110.png)

**Comment by tecrogue** [comment] 2019-06-23 23:48
Duplicate of #6

**Closed as completed by tecrogue** 2019-06-23 23:48 UTC
Labels: duplicate
